# See https://pre-commit.com for more information
repos:
  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]

  # Remove unused imports
  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: 
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --in-place

  # Trailing whitespace and file fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Optional: Add black formatter
  # - repo: https://github.com/psf/black
  #   rev: 23.12.1
  #   hooks:
  #     - id: black
  #       language_version: python3.9
  #       args: ["--line-length", "120"]

  # Note: pylint is excluded from pre-commit as it's slow
  # Run it separately with: uv run pylint *.py